### ISSUE TITLE
Xbox Elite 2 controller does not fully work?

### ISSUE THREAD

**Issue by WindmillWarrior** [Ultreon/ControllerX#4]
First of all, amazing mod, you are truly doing gods work. How Java version does not have the controller added native since MS took over is beyond me, but it's very handy when playing on a laptop.

Anyway, i am using a Elite 2 controller and some buttons don't function (sprint and crouch are mapped to pushing the joysticks and don't respond).

And i noticed that using the left trigger to place blocks has no cooldown, immediately placing as many blocks the second i touch the trigger.

It's probably solved when the mappable buttons come out, but just so you know :)

**Comment by XyperCode** [comment]
Those issues were worked on. Am currently busy working on a game.
Not sure how stable the current code is, but if you want to test it out I could try sending over a development build.
