### ISSUE TITLE
No Curseforge release planned?

### ISSUE THREAD

**Issue by shawny43** [Ultreon/ControllerX#7]
There no download or updates for Curseforge?

**Comment by XyperCode** [comment]
No idea what you're talking about...
It's there just fine:
https://www.curseforge.com/minecraft/mc-mods/controllerx

**Comment by shawny43** [comment]
> No idea what you're talking about...
> It's there just fine:
> https://www.curseforge.com/minecraft/mc-mods/controllerx

Wait how? I searched from client and I didn't find it. There a bug? I'm on 1.20.1

**Comment by XyperCode** [comment]
Are you sure you use a supported modloader? Quilt isn't supported.

**Comment by shawny43** [comment]
Im using Forge. Maybe the issue come from Curseforge himself. They have sometimes bad keywords algorithm over search in the past. Forced to use web version of it.

**Comment by shawny43** [comment]
Curseforge side issue somehow, i close to prevent misleading.
